replicaCount: 1

image:
  repository: nginx
  tag: stable

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  hosts:
    - <CHARTNAME>.local

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""
